version: "3"
services:
  websockets:
    build:
      context: .
      dockerfile: Dockerfile.websockets
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8020:8020"
      # - "80:80"
    depends_on:
      - websockets